name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        triplet: [x64-windows, x64-linux, x64-osx, arm64-osx]
        include:
          - triplet: x64-windows
            os: windows-latest
          - triplet: x64-linux
            os: ubuntu-latest
          - triplet: x64-osx
            os: macos-latest
          - triplet: arm64-osx
            os: macos-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: install uuid
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt install uuid-dev
    - name: configure debug
      run: cmake . -B build -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Debug
    - name: build debug
      run: cmake --build build --config Debug
    - name: unittests debug
      run: ./build/bin/Debug/mn_unittest
    - name: configure release
      run: cmake . -B build -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release
    - name: build release
      run: cmake --build build --config Release
    - name: unittests release
      run: ./build/bin/Release/mn_unittest
